export const FETCH_PROD_BY_FILTER_REQ = 'FETCH_PROD_BY_FILTER_REQ';
export const FETCH_PROD_GENERAL_REQ = 'FETCH_PROD_GENERAL_REQ';

export const FETCH_PROD_SUCCESS = 'FETCH_PROD_SUCCESS';
export const FETCH_PROD_FAILURE = 'FETCH_PROD_FAILURE';